language: node_js

node_js:
 - "7"

sudo: false

cache: yarn

before_install: 
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.21.3

script: 
- yarn run test:ci

after_success: -codecov  

before_deplay:
 - yarn run build
 - cp ./build/index.html ./build/200.html

deploy:
  provider: surge
  project: ./build/
  domain: slck.reactApp.surge.sh
  skip_cleanup: true